# Generated by Django 3.0.8 on 2020-08-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200811_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_post',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='network.Post'),
        ),
    ]
